### ISSUE TITLE
missing go-ipfs_v0.4.13_windows-386.zip ?

### ISSUE THREAD

**Issue by thisconnect** [ipfs/npm-go-ipfs-dep#23]
related https://github.com/ipfs/js-ipfsd-ctl/pull/176#issuecomment-355317761

**Comment by diasdavid** [comment]
go-ipfs failed to ship the 386 version due to badger issues, this will be fixed with the next release.

@whyrusleeping @Stebalien this is causing a considerable amount of pain. I know you have a bunch of features you are looking to ship the next version and so you have been holding for a big. Could you ship a 0.4.14 that has the current fixes including the windows build and ship the remaining features in a 0.4.15?

**Comment by whyrusleeping** [comment]
@diasdavid we're still working through some potential instability, and waiting on bubbling up some fixes for dialing issues. Are there that many 32 bit windows users?

**Comment by richardschneider** [comment]
go-ipfs issue: https://github.com/ipfs/go-ipfs/issues/4438

**Comment by mkg20001** [comment]
go-ipfs v0.4.14 has been released. I think this can be closed now.

**Comment by iamblue** [comment]
Mac also missing this file ...

```
Downloading https://dist.ipfs.io/go-ipfs/v0.4.14/go-ipfs_v0.4.14_darwin-amd64.tar.gz
/Users/apple/relajet/relajet-player-app/node_modules/go-ipfs-dep/src/index.js:102
      if (res.statusCode !== 200) {
```
